### ISSUE TITLE
Automatically add meta library locations to library issue

### ISSUE THREAD

**Issue by chiefkes** [metate/meta4kodi#14]
When I first installed meta, it asked me if I wanted it to automatically add its library locations to the kodi library. I clicked yes and items showed up in the library. However when I went to check videos > files, there was no meta tv shows/movies folder in there. Anticipating that I might have to remove and re-add items meta libary items during bug testing, I added the meta movies and tv shows locations manually. This of course led to double library entries. The only solution was either to remove the manually created folders (which would mean losing the ability to change content type to unassign/re-assign) or to delete the MyVideos99.db file. I opted for the later and then re-added the meta library folders manually. So I think there's a bug with the automatic library locations function.

**Comment by metate** [comment]
The sources would have appeared in gui if you restarted Kodi. 
Since the automatic library setup uses tons of hacks and there is no standard way to do it in Kodi I decided to drop this feature and let users add sources manually. That's unfortunate because new users usually have no idea how to do that but I prefer a clean and safe addon.

**Comment by metate** [comment]
Moved to https://github.com/metate/meta4kodi/issues/22 for better issue traking
